trigger:
  branches:
    include:
      - master  # Trigger pipeline on changes to master branch

pool:
  vmImage: 'windows-latest'  # Use Windows agent for MSBuild and NuGet tasks

steps:
# Install .NET SDK (for .NET 8.x)
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore dependencies using NuGet
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

# Build the solution using MSBuild
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile=FolderProfile'

# Publish build artifacts (for packaging or deployment)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'
    publishLocation: 'Container'

# Create the NuGet package using NuGetCommand
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)'

# Push the NuGet package to Azure Artifacts feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishVstsFeed: 'MyNuGetFeed'  # Replace with your actual feed name
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
